from ..commons.colors import GradientColor

SHAPE_LABEL_WIDTH = 100
HEIGHT_PER_TIME_SLICE = 30
PIXEL_PER_SECOND= 100.

SHAPE_NAME_HEIGHT = 30

TIME_LINE_BACKGROUND_COLOR = "eeeeee"

DRAW_AREA_PADDING = 5
TIME_STAMP_LABEL_HEIGHT = 20

SHAPE_LINE_LEFT_PADDING = 5
SHAPE_LINE_BOTTOM_PADDING = 10

PROP_LEFT_BACK_COLOR = "cccccc"
PROP_TIME_LINE_VERTICAL_PADDING = 5
PROP_NAME_LABEL_WIDTH = 100
PROP_NAME_LABEL_RIGHT_PADDING = 5
PROP_VALUE_LABEL_WIDTH = 20

SHAPE_NAME_BACK_COLOR = GradientColor.simple(("666666", "aaaaaa"))
SHAPE_NAME_BORDER_COLOR = "000000"
SHAPE_NAME_TEXT_COLOR = "000000"

END_POINT_HEIGHT = 10

PROP_NAME_BACK_COLOR = GradientColor.simple(("cccccc", "eeeeee"))
PROP_NAME_BORDER_COLOR = "333333"
PROP_NAME_TEXT_COLOR = "000000"

